VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsFractionAnnotationDescriptor"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public StartFraction As String
Public EndFraction As String
Public StartVolume As Double
Public EndVolume As Double
Public Color As Long
Public Name As String

