VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IExperiment"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'****************************************************************************************************
'====================================================================================================
'This is an interface all Experiments
'Juraj Ahel, 2016-05-09
'Last update 2016-05-09
'====================================================================================================
Option Explicit

Public Property Get ExpName() As String

End Property

Public Property Get ExpDate() As String

End Property

Public Property Get Scientist() As String

End Property

Public Property Get ExpType() As String

End Property



