VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IContainerSample"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get Name() As String

End Property

Public Property Let Name(N As String)

End Property

Public Property Get Location() As clsWorktableSampleLocation

End Property

Public Property Set Location(inLoc As clsWorktableSampleLocation)

End Property


